[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
sqlx = "0.8.6"
serde_json = "1.0.140"
aws-config = "1.6.3"
aws-sdk-dynamodb = "1.79.0"
aws-types = "1.3.7"
lapin = { workspace = true }
actix = { workspace = true }
actix-rt = { workspace = true }