services:
  app:
    build: .
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT:-http://localstack:4566}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_REGION=${S3_REGION:-us-east-1}
      - DATABASE_URL=postgres://yongyutjantaboot@localhost:5432/telemetry_db
    security_opt:
      - no-new-privileges:true
    depends_on:
      localstack:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  localstack:
    ports:
      - "${PORT_S3:-4566}:4566"
    image: localstack/localstack
    environment:
      - SERVICES=${LOCALSTACK_SERVICES:-s3,dynamodb}
      - DEBUG=${LOCALSTACK_DEBUG:-1}
      - PORT_S3=${PORT_S3:-4566}
      - PORT_DYNAMODB=${PORT_DYNAMODB:-4567}
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "./localstack-init.sh:/etc/localstack/init/ready.d/init-aws.sh"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: "curl -s localhost:${PORT_S3:-4566}/_localstack/init/ready | fgrep '\"completed\": true'"
      interval: 5s
      retries: 10
      timeout: 10s

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 5
      timeout: 10s

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=p3a
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-xD25pcSecure}
      - POSTGRES_DB=p3a_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-p3a}" ]
      interval: 5s
      retries: 5
      timeout: 10s